# Use Node.js image
FROM node:20.13.1-alpine3.19

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code
COPY . .

# Expose port 8000
EXPOSE 8000

# Start Express server
CMD ["node", "index.js"]
